# Generated by Django 4.2.7 on 2026-03-31 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('token_refresh', 'Token Refresh'), ('register', 'User Registration'), ('email_verified', 'Email Verified'), ('password_reset_request', 'Password Reset Request'), ('password_reset_success', 'Password Reset Success'), ('password_changed', 'Password Changed'), ('account_locked', 'Account Locked'), ('suspicious_activity', 'Suspicious Activity Detected'), ('token_revoked', 'Token Revoked')], db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='audit_logs_user_id_d685f3_idx'), models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audit_logs_ip_addr_932507_idx')],
            },
        ),
    ]
