# Generated by Django 4.2.7 on 2026-04-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('token_refresh', 'Token Refresh'), ('register', 'User Registration'), ('email_verified', 'Email Verified'), ('password_reset_request', 'Password Reset Request'), ('password_reset_success', 'Password Reset Success'), ('password_changed', 'Password Changed'), ('profile_updated', 'Profile Updated'), ('account_deleted', 'Account Deleted'), ('account_locked', 'Account Locked'), ('suspicious_activity', 'Suspicious Activity Detected'), ('token_revoked', 'Token Revoked')], db_index=True, max_length=50),
        ),
    ]
